### ISSUE TITLE
Handcuffs fix

### ISSUE THREAD

**Issue by TiBarification** [TiBarification/Jail-Warden-Pro#14]
Fix handcuffs, prisoners can stuck in world models.

**Comment by shanapu** [comment]
hi, in MyJB I insert a check from smlib `Client_IsLookingAtWall` to delimit this problem.
Players can be still moved into walls/obstacles but it's not so easy as before. 
It prevents this problem most of the time... not perfect but better than nothing.
https://github.com/shanapu/MyJailbreak/commit/857cf0429662166a0695891d26102eef573895b4

**Comment by TiBarification** [comment]
@shanapu do you want to combine plugins? MyJailBreak, and this one.

**Comment by TiBarification** [comment]
For non-stuck in wall, we can add check for target. Is target in wall, or something like this.

**Comment by shanapu** [comment]
> @shanapu do you want to combine plugins? MyJailBreak, and this one.

I'm not sure if that would work, to merge jwp & myjb, cause of their coding styles and different concepts.
But I'm already planning what's next after "first stable of MyJb" and I have some ideas for new (jailbreak)-projects. I can well imagine to work with you and other together on a (new) project as a team.
Let's talk in steam!

> For non-stuck in wall, we can add check for target. Is target in wall, or something like this.

When check is target  in wall, it's to late. he is in wall. maybe save last position and port him back. 
I thought about a check 'is there a wall or obstacle in radius of [location2](https://github.com/shanapu/MyJailbreak/blob/develop/addons/sourcemod/scripting/MyJailbreak/Modules/Warden/handcuffs.sp#L245)' or something.

**Comment by TiBarification** [comment]
Or add same sight check for target in 4 directions.

**Comment by shanapu** [comment]
check for target in 4 directions seems the easiest way. I will testing around with this tonight.

**Comment by shanapu** [comment]
> Or add same sight check for target in 4 directions.

It's difficult. 
Where to check for IsNearbyObstacle(Target)?  

On pick up - https://github.com/shanapu/MyJailbreak/blob/develop/addons/sourcemod/scripting/MyJailbreak/Modules/Warden/handcuffs.sp#L231
Bad cause: when you cuff a player to close to a obstacle you can't pick him up

On pick up & cuff em - https://github.com/shanapu/MyJailbreak/blob/develop/addons/sourcemod/scripting/MyJailbreak/Modules/Warden/handcuffs.sp#L231 & https://github.com/shanapu/MyJailbreak/blob/develop/addons/sourcemod/scripting/MyJailbreak/Modules/Warden/handcuffs.sp#L275
So you prevent a player is to close to a obstacle when cuff him.
Bad: you can't cuff them near a wall (player can stay near a wall to prevent get cuffed.)

Also bad: you can "throw" a player into the IsNearbyObstacle radius by moving fast. So he is in IsNearbyObstacle radius and can't picked up and moved out of the zone.

At the moment i only see to check IsNearbyObstacle for 'location2' https://github.com/shanapu/MyJailbreak/blob/develop/addons/sourcemod/scripting/MyJailbreak/Modules/Warden/handcuffs.sp#L245 where the cuffed player get moved to.

maybe I fail to see something. its late. Im tired.

This stock checks really good in this viewlines and in 4 way directions
![unbenannt](https://cloud.githubusercontent.com/assets/7787074/17879391/ed726bce-68f1-11e6-9b73-d932d48d3cf0.png)

`stock bool Client_IsNearbyObstacle(int client, float distance=40.0) 
{

```
float posEye[3], posEyeAngles[3], Origin[3];
bool IsNearbyObstacle = false;
bool IsNearbyObstacleEyeHigh = false;
bool IsNearbyObstacleFloorHigh = false;

GetClientEyePosition(client,    posEye);
GetClientAbsOrigin(client,      Origin);

posEyeAngles[0] = 0.0;
posEyeAngles[1] = 0.0;
posEyeAngles[2] = 0.0;

for(int i = 0; i < 4; i++)
{
    posEyeAngles[1] = posEyeAngles[1] + 90.0;

    Handle trace[2];

    trace[0] = TR_TraceRayFilterEx(posEye, posEyeAngles, MASK_SOLID, RayType_Infinite, myjb_TraceEntityFilter);
    trace[1] = TR_TraceRayFilterEx(Origin, posEyeAngles, MASK_SOLID, RayType_Infinite, myjb_TraceEntityFilter);

    for(int iT = 0; iT < 1; iT++)
    {
        if (TR_DidHit(trace[iT])) {

            if (TR_GetEntityIndex(trace[iT]) > 0) {
                CloseHandle(trace[iT]);
                return false;
            }

            float posEnd[3];

            TR_GetEndPosition(posEnd, trace[iT]);

            if (GetVectorDistance(posEye, posEnd, true) <= (distance * distance)) {
                IsNearbyObstacleEyeHigh = true;
            }

            if (GetVectorDistance(Origin, posEnd, true) <= (distance * distance)) {
                IsNearbyObstacleFloorHigh = true;
            }
        }
    }
    CloseHandle(trace[0]);
    CloseHandle(trace[1]);

    if(IsNearbyObstacleEyeHigh || IsNearbyObstacleFloorHigh) IsNearbyObstacle = true;



}
return IsNearbyObstacle;
```

}

public bool myjb_TraceEntityFilter(int entity, int contentsMask)
{
    return entity == 0;
}`

**Comment by TiBarification** [comment]
Your forgot, that `TR_GetEntityIndex` can return 0 as `World`. So if player 

## get stucked in the wall, it don't help. Try to keep >= 0.

Another method - is creating brush entity on target, and get their 
collisions. I don't actually tried, but if it works, would be nice.

**Comment by shanapu** [comment]
I played around with different methods and checks for Client Client_NearObstacle & Origin_NearObstacle for location2. Nothing works well. Maybe you find a nicely working solution, or we should try it with creating brush entity on target.
