### ISSUE TITLE
Скины за т и кт не устанавливаются.

### ISSUE THREAD

**Issue by stvolcz** [TiBarification/Jail-Warden-Pro#20]
Проблема заключается в установке плагином скинов за обе команды(т и кт соответственно), причём данная проблема характерна с любым стд. скином, однако информация о том, что скин был выдан имеется models\player\custom_player\legacy\ctm_gsg9_variantd.mdl.
Версия JWP на сервере dev 05d

**Comment by TiBarification** [comment]
Errors?

**Comment by stvolcz** [comment]
L 09/08/2016 - 18:36:56: [SM] Call stack trace:
L 09/08/2016 - 18:36:56: [SM]   [0] json_object_get
L 09/08/2016 - 18:36:56: [SM]   [1] Line 141, jwp/dev.sp::GetStatusEnd()
L 09/08/2016 - 18:36:56: [SM]   [3] SteamWorks_GetHTTPResponseBodyCallback
L 09/08/2016 - 18:36:56: [SM]   [4] Line 134, jwp/dev.sp::OnSteamWorksHTTPRequestCompleted()
L 09/08/2016 - 18:50:36: SourceMod error session started
L 09/08/2016 - 18:50:36: Info (map "ba_jail_trganes") (file "errors_20160908.log")
L 09/08/2016 - 18:50:36: [SM] Unable to load plugin "jwp_bequiet.smx": Could not find required plugin "voiceannounce_ex"
L 09/08/2016 - 18:50:47: Error log file session closed.
L 09/08/2016 - 18:51:23: SourceMod error session started
L 09/08/2016 - 18:51:23: Info (map "ba_jail_trganes") (file "errors_20160908.log")
L 09/08/2016 - 18:51:23: [SMJSON] Error in line 1, col 1: '[' or '{' expected near '<'
L 09/08/2016 - 18:51:23: [SM] Exception reported: Invalid <Object> handle 0 (error 4)
L 09/08/2016 - 18:51:23: [SM] Blaming: jwp_core.smx()
L 09/08/2016 - 18:51:23: [SM] Call stack trace:
L 09/08/2016 - 18:51:23: [SM]   [0] json_object_get
L 09/08/2016 - 18:51:23: [SM]   [1] Line 141, jwp/dev.sp::GetStatusEnd()
L 09/08/2016 - 18:51:23: [SM]   [3] SteamWorks_GetHTTPResponseBodyCallback
L 09/08/2016 - 18:51:23: [SM]   [4] Line 134, jwp/dev.sp::OnSteamWorksHTTPRequestCompleted()
L 09/08/2016 - 18:51:30: [SM] Exception reported: Handle 20701d1 is invalid (error 1)
L 09/08/2016 - 18:51:30: [SM] Blaming: sm_hosties.smx()
L 09/08/2016 - 18:51:30: [SM] Call stack trace:
L 09/08/2016 - 18:51:30: [SM]   [0] CloseHandle
L 09/08/2016 - 18:51:30: [SM]   [1] Line 258, hosties/muteprisoners.sp::MutePrisoners_RoundEnd()
L 09/08/2016 - 18:51:58: [SMJSON] Error in line 1, col 1: '[' or '{' expected near '<'
L 09/08/2016 - 18:51:58: [SM] Exception reported: Invalid <Object> handle 0 (error 4)
L 09/08/2016 - 18:51:58: [SM] Blaming: jwp_core.smx()
L 09/08/2016 - 18:51:58: [SM] Call stack trace:
L 09/08/2016 - 18:51:58: [SM]   [0] json_object_get
L 09/08/2016 - 18:51:58: [SM]   [1] Line 141, jwp/dev.sp::GetStatusEnd()
L 09/08/2016 - 18:51:58: [SM]   [3] SteamWorks_GetHTTPResponseBodyCallback
L 09/08/2016 - 18:51:58: [SM]   [4] Line 134, jwp/dev.sp::OnSteamWorksHTTPRequestCompleted()
L 09/08/2016 - 19:03:40: SourceMod error session started
L 09/08/2016 - 19:03:40: Info (map "ba_jail_trganes") (file "errors_20160908.log")
L 09/08/2016 - 19:03:40: [SM] Unable to load plugin "jwp_bequiet.smx": Could not find required plugin "voiceannounce_ex"
L 09/08/2016 - 19:03:40: [SM] Exception reported: Unable to load file cfg/jwp/laserbeam/colors.txt
L 09/08/2016 - 19:03:40: [SM] Blaming: jwp_laserbeam.smx()
L 09/08/2016 - 19:03:40: [SM] Call stack trace:
L 09/08/2016 - 19:03:40: [SM]   [0] SetFailState
L 09/08/2016 - 19:03:40: [SM]   [1] Line 325, jwp_laserbeam.sp::LoadMenus()
L 09/08/2016 - 19:03:40: [SM]   [2] Line 62, jwp_laserbeam.sp::OnPluginStart()
L 09/08/2016 - 19:03:40: [SM] Unable to load plugin "jwp_laserbeam.smx": Error detected in plugin startup (see error logs)
L 09/08/2016 - 19:03:42: [SM] Exception reported: [JWP|Skins] Unable to load config file cfg/jwp/skin/t_models.txt
L 09/08/2016 - 19:03:42: [SM] Blaming: jwp_skin.smx()
L 09/08/2016 - 19:03:42: [SM] Call stack trace:
L 09/08/2016 - 19:03:42: [SM]   [0] SetFailState
L 09/08/2016 - 19:03:42: [SM]   [1] Line 134, jwp_skin.sp::LoadSkinsFromFile()
L 09/08/2016 - 19:03:42: [SM]   [2] Line 65, jwp_skin.sp::OnMapStart()
L 09/08/2016 - 19:03:43: [jwp_guns.smx] Failed to open cfg/jwp/guns.txt
L 09/08/2016 - 19:03:43: [SM] Exception reported: Unable to open file mcolors.txt
L 09/08/2016 - 19:03:43: [SM] Blaming: jwp_mcoloring.smx()
L 09/08/2016 - 19:03:43: [SM] Call stack trace:
L 09/08/2016 - 19:03:43: [SM]   [0] SetFailState
L 09/08/2016 - 19:03:43: [SM]   [1] Line 140, jwp_mcoloring.sp::LoadColors()
L 09/08/2016 - 19:03:43: [SM]   [2] Line 31, jwp_mcoloring.sp::JWP_Started()
L 09/08/2016 - 19:03:43: [SM]   [4] Call_Finish
L 09/08/2016 - 19:03:43: [SM]   [5] Line 373, jwp_core.sp::Forward_NotifyJWPLoaded()
L 09/08/2016 - 19:03:43: [SM]   [6] Line 386, jwp_core.sp::OnReadyToStart()
L 09/08/2016 - 19:03:43: [SM]   [7] Line 131, jwp_core.sp::OnConfigsExecuted()
L 09/08/2016 - 19:03:43: [SM] Exception reported: Plugin not runnable

**Comment by stvolcz** [comment]
L 09/08/2016 - 18:51:23: [SMJSON] Error in line 1, col 1: '[' or '{' expected near '<'
L 09/08/2016 - 18:51:23: [SM] Exception reported: Invalid <Object> handle 0 (error 4)
L 09/08/2016 - 18:51:23: [SM] Blaming: jwp_core.smx()
L 09/08/2016 - 18:51:23: [SM] Call stack trace:
L 09/08/2016 - 18:51:23: [SM]   [0] json_object_get
L 09/08/2016 - 18:51:23: [SM]   [1] Line 141, jwp/dev.sp::GetStatusEnd()
L 09/08/2016 - 18:51:23: [SM]   [3] SteamWorks_GetHTTPResponseBodyCallback
L 09/08/2016 - 18:51:23: [SM]   [4] Line 134, jwp/dev.sp::OnSteamWorksHTTPRequestCompleted()
PutClientInServer: no info_player_start on level
L 09/08/2016 - 18:51:30: [SM] Exception reported: Handle 20701d1 is invalid (error 1)
L 09/08/2016 - 18:51:30: [SM] Blaming: sm_hosties.smx()
L 09/08/2016 - 18:51:30: [SM] Call stack trace:
L 09/08/2016 - 18:51:30: [SM]   [0] CloseHandle
L 09/08/2016 - 18:51:30: [SM]   [1] Line 258, hosties/muteprisoners.sp::MutePrisoners_RoundEnd()
L 09/08/2016 - 18:51:58: [SMJSON] Error in line 1, col 1: '[' or '{' expected near '<'
L 09/08/2016 - 18:51:58: [SM] Exception reported: Invalid <Object> handle 0 (error 4)
L 09/08/2016 - 18:51:58: [SM] Blaming: jwp_core.smx()
L 09/08/2016 - 18:51:58: [SM] Call stack trace:
L 09/08/2016 - 18:51:58: [SM]   [0] json_object_get
L 09/08/2016 - 18:51:58: [SM]   [1] Line 141, jwp/dev.sp::GetStatusEnd()
L 09/08/2016 - 18:51:58: [SM]   [3] SteamWorks_GetHTTPResponseBodyCallback
L 09/08/2016 - 18:51:58: [SM]   [4] Line 134, jwp/dev.sp::OnSteamWorksHTTPRequestCompleted()

**Comment by TiBarification** [comment]
старый сайт сдох, вот и ругается dev.sp, когда сайт починю не знаю
Убедитесь что все конфиги залиты на сервер.
`L 09/08/2016 - 19:03:42: [SM] Exception reported: [JWP|Skins] Unable to load config file cfg/jwp/skin/t_models.txt
L 09/08/2016 - 19:03:40: [SM] Exception reported: Unable to load file cfg/jwp/laserbeam/colors.txt`
быть не должно

**Comment by stvolcz** [comment]
Мне брать их с последнего dev?

**Comment by TiBarification** [comment]
да

**Comment by TiBarification** [comment]
Часть логов хранится в `addons/sourcemod/logs/JWP_Log.log`

**Comment by stvolcz** [comment]
Проблема осталась.

**Comment by stvolcz** [comment]
Your new player skin: models\player\custom_player\kuristaja\jailbreak\guard1\guard1.mdl

**Comment by TiBarification** [comment]
скин не ставится?
Путь правильный прописан?

**Comment by stvolcz** [comment]
models\player\custom_player\kuristaja\jailbreak\guard1\guard1.mdl

**Comment by stvolcz** [comment]
мб слеши заменить

**Comment by TiBarification** [comment]
попробуйте

**Comment by stvolcz** [comment]
результат отрицательный.

**Comment by stvolcz** [comment]
L 09/08/2016 - 20:43:55: [SM] Blaming: jwp_core.smx()

**Comment by stvolcz** [comment]
Вы можете исправить?

**Comment by TiBarification** [comment]
Скачайте https://github.com/TiBarification/Jail-Warden-Pro/releases/tag/dev-0.5e

**Comment by stvolcz** [comment]
Ничего не изменилось

**Comment by TiBarification** [comment]
Мало информации значит. Я не понимаю в чём у вас проблема

**Comment by stvolcz** [comment]
Скины не ставит за кт, но скин Кмд работает, в логах не ошибок.

**Comment by TiBarification** [comment]
содержимое ct_models.txt

**Comment by stvolcz** [comment]
"Models"
{
    "ct1"
    {
        "path"          "models/player/custom_player/kuristaja/jailbreak/guard1/guard1.mdl"
        "skin"          "0"
        "arms_path"     "" // Working only in CS:GO
    }
    "ct2"
    {
        "path"          "models/player/custom_player/kuristaja/jailbreak/guard2/guard2.mdl"
        "skin"          "0"
        "arms_path"     "" // Working only in CS:GO
    }
}

**Comment by TiBarification** [comment]
Попробуйте эту версию.

[jwp_skin.zip](https://github.com/TiBarification/Jail-Warden-Pro/files/464377/jwp_skin.zip)
На строчке 161 была закомментирована установка скина. Я даже не помню почему. Наверное тестил считывание конфига.

**Comment by stvolcz** [comment]
Результат положительный, спасибо.

**Comment by stvolcz** [comment]
Вопрос - я могу сколько угодно добавить строк для скинов?

**Comment by TiBarification** [comment]
> Вопрос - я могу сколько угодно добавить строк для скинов?

Вы ограничены лишь ОЗУ сервера

**Comment by stvolcz** [comment]
Можно ещё исходник)
