### ISSUE TITLE
Баланс для Jail сервера

### ISSUE THREAD

**Issue by stvolcz** [TiBarification/Jail-Warden-Pro#22]
Т.к. в контролку интегрировано множество модулей, которые раньше были отдельными плагинами, то сюда можно и добавить баланс команд(т.е. вместо обычного 1:1, а например на одного Кт приходиться 3 Т).

**Comment by TiBarification** [comment]
Думал балансом занимается плагин [JailBreakTeamBalance](https://forums.alliedmods.net/showthread.php?p=1411145)

**Comment by WhyFaust** [comment]
?

**Comment by TiBarification** [comment]
It will not be implemented as a module. It should be a standalone plugin.
