### ISSUE TITLE
Переделка модуля оружие

### ISSUE THREAD

**Issue by stvolcz** [TiBarification/Jail-Warden-Pro#23]
Модуль оружие выдаёт оружие через Кмд меню, но при этом не удаляет старое, которое находиться  в руках Кмд, поэтому прошу сделать удаление оружия их рук кмд.
(алгоритм такой: после выбора в меню оружия, оружие из рук кмд удаляется, затем ему даётся выбранное им оружия из кмд меню.)

**Comment by TiBarification** [comment]
Уже реализовано. В конфиге оружия параметр "drop".

**Comment by stvolcz** [comment]
Сорян, прост описание подразумевает что оружие можно выбросить, либо нет.
