### ISSUE TITLE
Командир недоступен

### ISSUE THREAD

**Issue by stvolcz** [TiBarification/Jail-Warden-Pro#24]
Периодически возникает проблема с невозможностью взять Кмд ([КОМАНДИР] Командир недоступен), в логах ошибок нет.

**Comment by stvolcz** [comment]
Версия JWP 1.0.5

**Comment by TiBarification** [comment]
jwp.cfg сюда и опишите подробнее последовательность ваших действий при выборе командира.

**Comment by stvolcz** [comment]
// How to choose warden 1:random 2:command 3:voting
// -
// Default: "2"
// Minimum: "1.000000"
// Maximum: "3.000000"
jwp_choose_mode "2"

// Protect menu from random selecting
// -
// Default: "1"
// Minimum: "0.000000"
// Maximum: "1.000000"
jwp_disable_antiflood "1"

// Time before warden randomly picked if choose mode = 1
// -
// Default: "5"
// Minimum: "1.000000"
// Maximum: "30.000000"
jwp_random_wait "5"

// Time for voting if choose mode = 3
// -
// Default: "30"
// Minimum: "10.000000"
// Maximum: "60.000000"
jwp_vote_time "30"

// Enable (1) or disable (0) auto update. Need Updater!
// -
// Default: "0"
// Minimum: "0.000000"
// Maximum: "1.000000"
jwp_autoupdate "0"

**Comment by stvolcz** [comment]
Начало раунда, я пишу !w кмд берёт, а в следующем пишет , что кмд недоступен.

**Comment by stvolcz** [comment]
Причём когда 1 на сервере всё нормально, но зашёл человек для теста и появились баги

**Comment by TiBarification** [comment]
А когда 2 и более человек?

**Comment by stvolcz** [comment]
2 включая меня

**Comment by stvolcz** [comment]
а когда больше 1 - го баг

**Comment by TiBarification** [comment]
Воспроизвёл ситуацию, подобного не обнаружил.

**Comment by stvolcz** [comment]
Есть другая закономерность, когда я 1 контролка работает, но как только зашёл человек, она пишет что командир недоступен.

**Comment by TiBarification** [comment]
тестил с ботами и нормально

**Comment by stvolcz** [comment]
Однако есть подтверждение, что что - то не так:
 [КОМАНДИР] Чтобы стать командиром, пишите в чат !w
 [КОМАНДИР] Чтобы стать командиром, пишите в чат !w

**Comment by stvolcz** [comment]
2 раза выдаёт это сообщение, а когда всё нормально только 1 раз

**Comment by TiBarification** [comment]
Буду благодарен если поможете с тестами. Мой профиль в [steam](http://steamcommunity.com/id/doctor_white)

**Comment by stvolcz** [comment]
Добавил.
