### ISSUE TITLE
Двери джайлов не открываються

### ISSUE THREAD

**Issue by stvolcz** [TiBarification/Jail-Warden-Pro#25]
Проблема в том, что двери джайлов через кмд не открываются, причём оба варианта открытия дверей (открыть все двери и aim открытие дверей), пишет Не флуди командой, подожди 3 с.

Кроме JWP  нет плагинов. Версия 1.0.5

**Comment by stvolcz** [comment]
Ошибок в логах нет.

**Comment by TiBarification** [comment]
`Не флуди командой, подожди 3 с.` чтобы не злоупотребляли. Отключается в главном конфиге jwp.cfg.

**Comment by stvolcz** [comment]
Оно всегда так пишет, вне зависимости от времени.

**Comment by stvolcz** [comment]
При активации функции открытия дверей, выдаёт сообщение "Не флуди командой, подожди 3 с.", после чего закрывает меню и не активирует функцию.

**Comment by TiBarification** [comment]
После открытия дверей такое не может писать. Такое пишет только если очень много раз тыкать на пункт в меню. (ИМХО защита от дурака)

**Comment by stvolcz** [comment]
Я видимо неправильно ситуацию расписал, я жму пункт в меню "открыть все двери" и оно выдаёт сообщение  "Не флуди командой, подожди 3 с." , но при этом двери не открывает и это сообщение выдаётся всегда при использовании именно этого пункта.

**Comment by TiBarification** [comment]
Вечером гляну. И спасибо за активное тестирование. Это даёт мне понять, что плагин важен и его стоит развивать.

**Comment by TiBarification** [comment]
Как видите всё нормально.
![screenshot_2](https://cloud.githubusercontent.com/assets/6222472/18561317/0977a7d2-7b88-11e6-836a-1db794d5f17c.jpg)

**Comment by stvolcz** [comment]
На старых версиях работает ,но на 1.0.5 нет.

**Comment by TiBarification** [comment]
Стоит 1.0.5 и открывает/закрывает. Работает же. Видео можете сделать чтобы показать.

**Comment by stvolcz** [comment]
Мб я вам в скайпе покажу.

**Comment by stvolcz** [comment]
Ну так что?

**Comment by sp115-29** [comment]
Ну у меня то все работает.

**Comment by stvolcz** [comment]
Хорошо, как тогда полностью отключить защиту от флуда?

**Comment by TiBarification** [comment]
Квар же есть.

**Comment by stvolcz** [comment]
А где и как называется?

**Comment by TiBarification** [comment]
https://github.com/TiBarification/Jail-Warden-Pro/blob/master/cfg/jwp/jwp.cfg

**Comment by stvolcz** [comment]
jwp_disable_antiflood "0"

**Comment by TiBarification** [comment]
А на 1 поставить.

**Comment by stvolcz** [comment]
Оно по дефолту на 1 стояло, и проблема не исчезла.

**Comment by TiBarification** [comment]
Исправлено в коммите  fc7a232

## Загрузите версию 1.0.5А

Fixed in commit fc7a232
Download version 1.0.5A
