### ISSUE TITLE
Огонь по своим(FF)

### ISSUE THREAD

**Issue by stvolcz** [TiBarification/Jail-Warden-Pro#26]
Не работает модуль FF(friendly fire), т.е. при активации соответствующего пункта в меню, выдаёт сообщение в чате: 
Переменная сервера 'mp_friendlyfire' изменена на 1
 [КОМАНДИР] Дружественный огонь:ВКЛЮЧЕН
При ударе дружественного игрока выдаёт стандартные сообщения о френдли файере, даже кровь есть, но дамаг не наноситься.

**Comment by TiBarification** [comment]
Смотрите в сторону кваров, что ограничивают стрельбу по своим. Плагин тут не причём.
