### ISSUE TITLE
Crash log jwp_core.smx

### ISSUE THREAD

**Issue by fakeoff0** [TiBarification/Jail-Warden-Pro#29]
L 12/07/2016 - 21:59:29: Info (map "ba_jail_rebellion_fix") (file "errors_20161207.log")
L 12/07/2016 - 21:59:29: [SM] Exception reported: String formatted incorrectly - parameter 3 (total 2)
L 12/07/2016 - 21:59:29: [SM] Blaming: jwp_core.smx
L 12/07/2016 - 21:59:29: [SM] Call stack trace:
L 12/07/2016 - 21:59:29: [SM]   [0] ThrowNativeError
L 12/07/2016 - 21:59:29: [SM]   [1] Line 89, jwp/jwpm_menu.sp::Cmd_ShowMainMenu
L 12/07/2016 - 21:59:29: [SM]   [3] JWP_ShowMainMenu
L 12/07/2016 - 21:59:29: [SM]   [4] Line 96, jwp_slay.sp::SlayMenu_Callback
L 12/07/2016 - 23:01:00: Error log file session closed.

Listing 6 plugins:
  [01] SourceMod (1.8.0.5963) by AlliedModders LLC
  [02] CS Tools (1.8.0.5963) by AlliedModders LLC
  [03] SDK Tools (1.8.0.5963) by AlliedModders LLC
  [04] SDK Hooks (1.8.0.5963) by AlliedModders LLC
  [05] SteamWorks Extension (1.2.1) by Kyle Sanderson
  [06] DHooks (2.1.0) by Dr!fter

[SM] Listing 74 plugins:
  01 "[JWP] Warden Timer" (1.0) by White Wolf
  02 "Anti-Flood" (1.8.0.5963) by AlliedModders LLC
  03 "Sound Commands" (1.8.0.5963) by AlliedModders LLC
  04 "[Jail Games] Defence" (1.0) by NoTiCE
  05 "SuperAdminka" (1.4.7) by Grey
  06 "[JWP] Manual Coloring" (1.0) by White Wolf
  07 "[JWP] Play Sound" (1.0) by White Wolf
  08 "[JWP] Core" (1.0.6B) by White Wolf & TiBarification
  09 "[JWP] Transfer warden" (1.1) by White Wolf
  10 "MyJailShop" (1.2.0-ff25d8e) by shanapu
  11 "Smart Jail Doors" (0.5.2-beta) by Maxim 'Kailo' Telezhenko
  12 "Fun Votes" (1.8.0.5963) by AlliedModders LLC
  13 "Basic Info Triggers" (1.8.0.5963) by AlliedModders LLC
  14 "[JWP] Door Control" (1.3) by White Wolf & Kailo97 (dev of doors plugin)
  15 "[JWP] Skin" (1.3) by White Wolf
  16 "[JWP] Prisoner Counter" (1.4) by White Wolf
  17 "[JWP] Round Extender" (1.3) by White Wolf
  18 "[JWP] Door Aim Control" (1.3) by White Wolf
  19 "[JWP] Order" (1.2) by White Wolf
  20 "SM File/Folder Downloader and Precacher" (1.4) by SWAT_88
  21 "CS:GO Goremod" (1.3) by Joe 'DiscoBBQ' Maley
  22 "Basic Votes" (1.8.0.5963) by AlliedModders LLC
  23 "[JWP] Noblock" (1.3) by White Wolf
  24 "Team Balance (CT 1 - T 'x')" (1.2) by wS (World-Source.Ru)
  25 "[JWP] Friendly Fire" (1.2) by White Wolf
  26 "[JWP] Freeday no weapon & rebel" (1.0) by White Wolf
  27 "Jail Games (Core plugin)" (1.0) by NoTiCE
  28 "IP Name & Say Block" (2.0) by R1KO
  29 "[JWP] Admin Control" (1.3) by White Wolf
  30 "Admin File Reader" (1.8.0.5963) by AlliedModders LLC
  31 "Client Preferences" (1.8.0.5963) by AlliedModders LLC
  32 "[JWP] To Jail" (1.1) by White Wolf
  33 "[JWP] Otkaz Module" (1.2) by White Wolf
  34 "SwapTeam" (1.2.6) by Rogue - Originally by MistaGee
  35 "Реклама" (1.2) by Pheonix (‰7Феникс7‰)
  36 "[JWP] Stop LR" (1.2) by White Wolf
  37 "[JWP] Rebel" (1.6) by White Wolf
  38 "[JWP] Warden color" (1.3) by White Wolf
  39 "Basic Ban Commands" (1.8.0.5963) by AlliedModders LLC
  40 "[JWP] Warden health" (1.3) by White Wolf
  41 "Player Commands" (1.8.0.5963) by AlliedModders LLC
  42 "SM_Hosties v2" (2.1.3b) by databomb & dataviruset & comando
  43 "[JWP] Laser Beam" (1.4) by White Wolf
  44 "[JWP] Respawn" (1.2) by White Wolf
  45 "[JWP] Handcuffs" (1.3) by White Wolf
  46 "[JWP] Freeday" (1.3) by White Wolf
  47 "[CS:GO/CSS] AbNeR Round End Sounds Simple" (3.4) by AbNeR_CSS
  48 "Rules Plugin" (1.3) by haN
  49 "Basic Comm Control" (1.8.0.5963) by AlliedModders LLC
  50 "VoiceAnnounceEx" (2.1.1) by Franc1sco franug, Mini and GoD-Tony
  51 "[JWP] Mute" (1.2) by White Wolf
  52 "Thirdperson Mode" (3.1.0) by Zephyrus & Justkasi
  53 "Basic Commands" (1.8.0.5963) by AlliedModders LLC
  54 "Admin Help" (1.8.0.5963) by AlliedModders LLC
  55 "[JWP] MultiGames" (0.52) by White Wolf
  56 "[JWP] Icon" (1.0) by White Wolf
  57 "Reserved Slots" (1.8.0.5963) by AlliedModders LLC
  58 "[JWP] Strip Knife" (1.2) by White Wolf
  59 "Basic Chat" (1.8.0.5963) by AlliedModders LLC
  60 "[JWP] Pointer" (1.0) by White Wolf
  61 "Nextmap" (1.8.0.5963) by AlliedModders LLC
  62 "Fun Commands" (1.8.0.5963) by AlliedModders LLC
  63 "AWP Zeus lightning bullets" (1.0) by Hipster/Panduh (AlliedMods: thetwistedpanda)/TheBadTurtle(kupah)
  64 "[JWP] Coloring" (1.2) by White Wolf
  65 "[JWP] Be quiet" (1.3) by Fastmancz & White Wolf
  66 "[JWP] Guns" (1.3) by White Wolf
  67 "[JWP] Isolator" (1.2) by White Wolf
  68 "[JWP] Speed" (1.3) by White Wolf
  69 "[JWP] Slay" (1.3) by White Wolf
  70 "Admin Menu" (1.8.0.5963) by AlliedModders LLC
  71 "[JWP] On LR Started" (1.2) by White Wolf
  72 "[JWP] Shootguns" (1.0) by White Wolf
  73 "[JWP] Health Kit" (1.3) by White Wolf
  74 "Spawn Time Control" (1.2) by wS (World-Source.Ru)

**Comment by TiBarification** [comment]
@vovo4ka960 thank you for this issue.
It will be fixed in the next update.
