### ISSUE TITLE
Добавить в jwp_handcuffs

### ISSUE THREAD

**Issue by kerillovi4** [TiBarification/Jail-Warden-Pro#32]
Прошу добавить в jwp_handcuffs.smx

1. Чтобы при спавне КТ выдавалось автоматически "Teser", или выдачу "Teser" по коменде (!t или !z ну или другая какая команда)
2. Сделать сообщение в чате: "[Арест] {1} арестовал {2}" добавить цвета: "{DEFAUlT}[{GREEN}Арест{DEFAUlT}] {BLUE}{1} {DEFAUlT}арестовал {RED}{2}"
3. При нажатии на кнопку в меню кмд: "Снять арест" можно было выбрать у кого снять

**Comment by TiBarification** [comment]
I will look into it later. Maybe in the next huge update.

**Comment by TiBarification** [comment]
[jwp_handcuffs.zip](https://github.com/TiBarification/Jail-Warden-Pro/files/685603/jwp_handcuffs.zip)

1. Use "sm_hosties_ct_start" cvar, simply add "weapon_taser".
2. Implemented in new commit. 5f52267
3. I don't think it must to be, you can release T by tasing him again.
