### ISSUE TITLE
+ Возможность

### ISSUE THREAD

**Issue by Fixlenskiy** [TiBarification/Jail-Warden-Pro#33]
1. Добавить возможность голосования , за перекидывание кт за т (создавать голосование может кмд)
2. Добавить возможность ставить в наручники кт
3. Добавить автоматическую выдачу зевса кмд
4. Добавить похожую иконку для зам кмд
5. Добавить создание кругов для кмд

6. добавить зекам меню , в котором можно встать в очередь на кт
7. добавить голосование за смену кмд
8. Добавить отказ приказа

**Comment by TiBarification** [comment]
1. I look into it
2. I don't really know, what you mean about that
3. Use "sm_hosties_ct_start" cvar, in hosties, add "weapon_taser".
4. Already in process [JWP] Icon update to icon another players depending on their status
5. https://scriptplugs.info/resources/jwp-pointer.2/
6. It makes this plugin more complex. I think it could be another plugin, that works only with balance.
7. I look into it
8. [Otkaz plugin](https://github.com/TiBarification/Otkaz) + [[JWP] Otkaz module](../blob/master/addons/sourcemod/scripting/jwp_otkaz_m.sp)

**Comment by Fixlenskiy** [comment]
2. С Зевса можно ставить в наручники Зеков , сделай чтобы можно было КМД ставить охрану в наручники с Зевса

**Comment by TiBarification** [comment]
2. I think that the warden doesn't need such a function, some mischief can be obtained.

**Comment by WhyFaust** [comment]
1)Бред,есть для этого администрация с кт баном
2)...
3)...
4)...
5)Думаю будет хорошо сделать бесплатным что то из материалов,а не партиклей
6)jwp_ratio + menu_creator
7)jwp_wvotekick
8)...
