### ISSUE TITLE
Ошибка перевода в jwp_modules.phrases.txt

### ISSUE THREAD

**Issue by kerillovi4** [TiBarification/Jail-Warden-Pro#36]
Строки 116, 117, 122, 123
Ошибки в слове {DEFALULT} на всех 4 строках, должно быть {DEFAULT}

:)

**Comment by TiBarification** [comment]
I know this issue, and it already fixed, just redownload `jwp phrases` 
from repository.


10.01.2017 15:06, RealFaya пишет:
>
> Строки 116, 117, 122, 123
> Ошибки в слове {DEFALULT} на всех 4 строках, должно быть {DEFAULT}
>
> :)
>
