### ISSUE TITLE
Errors jwp.core

### ISSUE THREAD

**Issue by fakeoff0** [TiBarification/Jail-Warden-Pro#37]
L 01/10/2017 - 18:55:03: Info (map "ba_jail_Bravo") (file "errors_20170110.log")
L 01/10/2017 - 18:55:03: [SM] Exception reported: Invalid <JSON Object> handle 0 (error 4)
L 01/10/2017 - 18:55:03: [SM] Blaming: jwp_core.smx
L 01/10/2017 - 18:55:03: [SM] Call stack trace:
L 01/10/2017 - 18:55:03: [SM]   [0] json_typeof
L 01/10/2017 - 18:55:03: [SM]   [1] Line 970, /home/travis/build/TiBarification/Jail-Warden-Pro/addons/sourcemod/scripting/include/smjansson.inc::json_object_get_bool
L 01/10/2017 - 18:55:03: [SM]   [2] Line 233, jwp/dev.sp::GetStatusEnd
L 01/10/2017 - 18:55:03: [SM]   [4] SteamWorks_GetHTTPResponseBodyCallback
L 01/10/2017 - 18:55:03: [SM]   [5] Line 223, jwp/dev.sp::OnSteamWorksHTTPRequestCompleted
L 01/10/2017 - 18:56:38: Error log file session closed.

**Comment by TiBarification** [comment]
Bug minor and i think it's not important. But i try to fix it.
