### ISSUE TITLE
Pointer + Neon

### ISSUE THREAD

**Issue by fakeoff0** [TiBarification/Jail-Warden-Pro#39]
Добавить в jwp.pointer неон, чтобы в центре указателя был неон синего цвета
Будет смотреться интересно!
Тем более на некоторых картах Jail не видно синие частицы указателя, из-за яркости карты. А лишь красную стрелку
https://scriptplugs.info

**Comment by TiBarification** [comment]
Здесь публикуются проблемы или пожелания только для публичных аддонов. Приватные просьба тут не обсуждать.
