### ISSUE TITLE
+Функции jwp 

### ISSUE THREAD

**Issue by fakeoff0** [TiBarification/Jail-Warden-Pro#40]
1. При включение Noblock игроков выталкивало друг из друга, чтобы не застревали
2. Не высвечивает в меню Кмд функцию Mute 
3. При при выборе Кмд через voting, не высвечивалось меню с Кмд
4. Убрать когда Кмд говорит hsay: Всем слушать Кмд   (Перебивает когда Кмд говорит плагин shop jihad, осчет до взрыва или кейс тоже например)   Кмд и так все слушают, всех загрушает
5. Звук для всех Когда Кмд сменился

**Comment by TiBarification** [comment]
1. Затруднительно реализовать
2. Значит нет прав на функцию mute.
3. Подробнее
4. Просто отключите необходимый модуль (jwp_bequiet)
5. Возможно добавлю

**Comment by fakeoff0** [comment]
3. Когда Кмд выбирают через голосование, нужно чтобы у него не высвечивалось меню кмд, а только через !w
4. Мне нужно чтобы он работал, это удобный очень модуль глушит Т. Хочу лишь убрать чтобы не писало в hsay это: Слушайте приказ КМД

**Comment by TiBarification** [comment]
3. Added in commit 674730cb
4. Позже сделаю отдельным кваром чтоб выключать.
