### ISSUE TITLE
Дополнительные функции

### ISSUE THREAD

**Issue by fakeoff0** [TiBarification/Jail-Warden-Pro#47]
1. Вызвать меню Кмд при нажатие E (Очень удобно не нужно прописывать в чате)
2. Меню зама. (Так же как и warden_menu только с замом)

**Comment by TiBarification** [comment]
1. Подумаю над этим, если будет востребовано, сделаю.
2. Меню сильно связано с командиром. А менять все ради зама не считаю рациональным.

**Comment by WhyFaust** [comment]
1.сделать таймер,после которого идёт проверка,есть ли кмд,если нет то открываются двери и всем фд
2.Заняться оформлением плагинов на hlmod,то есть отдельно ядро ,отдельно модули,к каждому описание и т.п.(Могу помочь с реализацией)

**Comment by TiBarification** [comment]
**Просьба не писать все предложения/баги в одной ветке задачи(issue).**
1. Можно реализовать
2. По поводу оформления на hlmod. Я уже пробовал так сделать, но в связи с большим количеством модулей проще выкладывать все обновы в одной теме. Здесь у меня настроена автоматическая сборка(компиляция) и деплой(выгрузка) в [Releases](./../releases)

**Comment by TiBarification** [comment]
Не востребовано
