### ISSUE TITLE
Not enough space on the heap in JWP Core

### ISSUE THREAD

**Issue by WhyFaust** [TiBarification/Jail-Warden-Pro#49]
```
L 03/26/2017 - 13:36:57: [SM] Exception reported: Not enough space on the heap
L 03/26/2017 - 13:36:57: [SM] Blaming: jwp_core.smx
L 03/26/2017 - 13:36:57: [SM] Call stack trace:
L 03/26/2017 - 13:36:57: [SM]   [1] Line 621, C:\Users\Faust-PC\Desktop\scripting\jwp_core.sp::JWP_GetRandomTeamClient
L 03/26/2017 - 13:36:57: [SM]   [2] Line 573, C:\Users\Faust-PC\Desktop\scripting\jwp_core.sp::JWP_FindNewWarden
L 03/26/2017 - 13:36:57: [SM]   [3] Line 439, C:\Users\Faust-PC\Desktop\scripting\jwp_core.sp::RemoveCmd
L 03/26/2017 - 13:36:57: [SM]   [4] Line 46, jwp/natives.sp::Native_SetWarden
```

**Comment by TiBarification** [comment]
Я попробовал увеличить размер памяти в куче (heap).
Добавил директиву
```h
#pragma dynamic 30562
```

Попробуйте использовать эту версию и скажите результат.

[jwp_core.zip](https://github.com/TiBarification/Jail-Warden-Pro/files/870742/jwp_core.zip)

**Comment by WhyFaust** [comment]
```
L 03/26/2017 - 16:34:42: [SM] Exception reported: Not enough space on the stack
L 03/26/2017 - 16:34:42: [SM] Blaming: jwp_core.smx
L 03/26/2017 - 16:34:42: [SM] Call stack trace:
L 03/26/2017 - 16:34:42: [SM]   [0] Call_Finish
L 03/26/2017 - 16:34:42: [SM]   [1] Line 20, D:\Addons\GitHub\Jail Warden Pro\addons\sourcemod\scripting\jwp/forwards.sp::Forward_OnWardenChoosing
L 03/26/2017 - 16:34:42: [SM]   [2] Line 546, D:\Addons\GitHub\Jail Warden Pro\addons\sourcemod\scripting\jwp_core.sp::JWP_FindNewWarden
L 03/26/2017 - 16:34:42: [SM]   [3] Line 441, D:\Addons\GitHub\Jail Warden Pro\addons\sourcemod\scripting\jwp_core.sp::RemoveCmd
L 03/26/2017 - 16:34:42: [SM]   [4] Line 46, D:\Addons\GitHub\Jail Warden Pro\addons\sourcemod\scripting\jwp/natives.sp::Native_SetWarden
```

**Comment by TiBarification** [comment]
Попробуйте это.
```h
#pragma dynamic 104584
```
[jwp_core.zip](https://github.com/TiBarification/Jail-Warden-Pro/files/870790/jwp_core.zip)

**Comment by WhyFaust** [comment]
```
L 03/26/2017 - 16:56:27: [SM] Exception reported: Not enough space on the stack
L 03/26/2017 - 16:56:27: [SM] Blaming: jwp_core.smx
L 03/26/2017 - 16:56:27: [SM] Call stack trace:
L 03/26/2017 - 16:56:27: [SM]   [0] Call_Finish
L 03/26/2017 - 16:56:27: [SM]   [1] Line 20, D:\Addons\GitHub\Jail Warden Pro\addons\sourcemod\scripting\jwp/forwards.sp::Forward_OnWardenChoosing
L 03/26/2017 - 16:56:27: [SM]   [2] Line 546, D:\Addons\GitHub\Jail Warden Pro\addons\sourcemod\scripting\jwp_core.sp::JWP_FindNewWarden
L 03/26/2017 - 16:56:27: [SM]   [3] Line 441, D:\Addons\GitHub\Jail Warden Pro\addons\sourcemod\scripting\jwp_core.sp::RemoveCmd
L 03/26/2017 - 16:56:27: [SM]   [4] Line 46, D:\Addons\GitHub\Jail Warden Pro\addons\sourcemod\scripting\jwp/natives.sp::Native_SetWarden
```

**Comment by TiBarification** [comment]
Попробуйте так:
```h
#pragma dynamic 1045840
```
[jwp_core.zip](https://github.com/TiBarification/Jail-Warden-Pro/files/870821/jwp_core.zip)
Если не поможет, то придётся менять алгоритм поиска рандомного клиента.

**Comment by TiBarification** [comment]
Какая у вас версия SourceMod?

**Comment by WhyFaust** [comment]
1.8
Да,последняя версия решила проблему

**Comment by TiBarification** [comment]
Если за неделю проблем не будет, посчитаем проблему решённой.

**Comment by WhyFaust** [comment]
Снова появилась такая же ошибка(

**Comment by TiBarification** [comment]
>Снова появилась такая же ошибка(

Подробнее, может лог?

**Comment by WhyFaust** [comment]
https://drive.google.com/open?id=0B1FT9wO-Nia_S0lOaU14NUFCSlk
Примерно вот так

**Comment by TiBarification** [comment]
Изменил алгоритм функции, на которую ругался см в начале.

Попробуйте эту версию:


[jwp_core.zip](https://github.com/TiBarification/Jail-Warden-Pro/files/870954/jwp_core.zip)

**Comment by WhyFaust** [comment]
https://drive.google.com/open?id=0B1FT9wO-Nia_S0lOaU14NUFCSlk
Чуток вроде ошибки другие стали

**Comment by TiBarification** [comment]
Напишите результат от ввода в консоль сервера `sm plugins info jwp_core.smx`

**Comment by WhyFaust** [comment]
sm plugins info jwp_core.smx
```
Filename: jwp_core.smx
Title: [JWP] Core (Jail Warden Pro Core)
Author: White Wolf & TiBarification
Version: 1.1.2 [Patch #4]
URL: https://scriptplugs.info http://hlmod.ru http://steamcommunity.com/id/doc
tor_white
Status: running
Timestamp: 03/26/2017 21:38:53
Hash: 7d376373b0656fa38db34ae0cace7c8c
```

**Comment by TiBarification** [comment]
Да уж, проблема вообще не очивидна, похоже сурсмод выпендривается. Т.к. пишет что скрипту нехватает памяти.

**Comment by WhyFaust** [comment]
В игре это примерно происходит так: проходит заданное время (jwp_vote_time "15")
После чего в игровой чат пишется 99999 раз что новый Командир (NICK),но кмд становятся все ктшники

P.S.Командир вообще как бы не должен выбираться в игр.день

**Comment by WhyFaust** [comment]
И с  последней версией сервер нагружает на 999%)

**Comment by TiBarification** [comment]
Требуется пошаговое воспроизведение проблемы.

1. ...
2. ...
3. ...

**Comment by WhyFaust** [comment]
Сейчас напишу,при стандартном ядре пишутся ещё вот эти строки
```
L 03/29/2017 - 18:30:25: [SM] Exception reported: Heap leak detected: hp:15036 should be 14916!
L 03/29/2017 - 18:30:25: [SM] Exception reported: Invalid plugin address
```

**Comment by WhyFaust** [comment]
1)Кмд выбирает игру
2)Начало раунда и в чат начинает спамить
НОВЫЙ КМД : CONSOLE фраз 100
-Это если выбор кмд голосованием
-Если командой,то это пишет только тогда,когда кт пишет !w

**Comment by mrkos9i4ok** [comment]
НАШЛОСЬ РЕШЕНИЕ
------------------------------------
Поставил ядро версией 1.1.1 и с его иклюдами перекомпилировал,в данный момент всё работает.

**Comment by WhyFaust** [comment]
Ну вот самые свежие ошибки)
https://drive.google.com/open?id=0B1FT9wO-Nia_SVcxMmFKanVDVTA

**Comment by TiBarification** [comment]
Утечка памяти.
Вы всё ещё на версии 1.1.1? Если так, то я её уже не поддерживаю.

**Comment by WhyFaust** [comment]
Нет,на версии 1.1.1 всё нормально, ошибки на 1.1.2

**Comment by TiBarification** [comment]
Любопытно, однако изменения в версии 1.1.2 незначительные.
