### ISSUE TITLE
Сommander fired

### ISSUE THREAD

**Issue by fakeoff0** [TiBarification/Jail-Warden-Pro#51]
Добавить голосование по увольнение командира обычным игрокам
Причину увольнение
~~Добавление в бан КТ и срок бана зависит от выбора нарушение правил~~

**Comment by WhyFaust** [comment]
КТ Бан у всех мб разный,и вы хотите сказать к каждому делать поддержку?

**Comment by TiBarification** [comment]
Причем тут ктбан к кмд?

**Comment by WhyFaust** [comment]
> Добавление в бан КТ и срок бана зависит от выбора нарушение правил

Можно просто Голосование,через к примеру 9/16 голосов его бы перекидывало за Т-команду

**Comment by TiBarification** [comment]
Кто может голосовать?

**Comment by WhyFaust** [comment]
Только зеки

**Comment by TiBarification** [comment]
Живые и мертвые?

**Comment by WhyFaust** [comment]
Ну да,все

**Comment by TiBarification** [comment]
А что если они начнут без причины выгонять голосованием?

**Comment by WhyFaust** [comment]
сделать настраиваемый процент,к примеру 70% от общего кол-ва зеков
Ну если 7 из 10 хотят выгнать значит уже есть за что,им не нравится как он командует или т.п.
Зайдёт другой
Не если что его же просто за Т,захочет мб ещё раз зайдет :3

**Comment by TiBarification** [comment]
И так они смогут выгнать каждого кт?

**Comment by WhyFaust** [comment]
сделать ограничение,ну типо 1 за раунд ну или же просто каждого разрешить

**Comment by TiBarification** [comment]
>просто каждого разрешить

Я не понял этой формулировки

**Comment by WhyFaust** [comment]
> они смогут выгнать каждого кт

**Comment by TiBarification** [comment]
Check
[jwp_votewardenkick.zip](https://github.com/TiBarification/Jail-Warden-Pro/files/887674/jwp_votewardenkick.zip)
Command:

- sm_wvotekick

**Comment by WhyFaust** [comment]
какая команда?

**Comment by TiBarification** [comment]
sm_wvotekick

**Comment by TiBarification** [comment]
Reference 059a686

**Comment by WhyFaust** [comment]
Вроде всё работает,ещё бы команду полегче сделать)
Типо !ctkick

**Comment by fakeoff0** [comment]
Есть такая ситуация: Командир не зная правил играет за КТ, с него снимают командира, но он продолжает командовать нарушая правила.
Можно сделать чтобы еще переводило за Т?

**Comment by WhyFaust** [comment]
L 04/09/2017 - 20:07:24: [SM] Exception reported: Client index 1702129494 is invalid (arg 3)
L 04/09/2017 - 20:07:24: [SM] Blaming: jwp_votewardenkick.smx
L 04/09/2017 - 20:07:24: [SM] Call stack trace:
L 04/09/2017 - 20:07:24: [SM]   [0] VFormat
L 04/09/2017 - 20:07:24: [SM]   [1] Line 68, C:\Users\Faust-PC\Desktop\scripting\include\multicolors.inc::CPrintToChatAll
L 04/09/2017 - 20:07:24: [SM]   [2] Line 105, jwp_votewardenkick.sp::VoteForPlayer
L 04/09/2017 - 20:07:24: [SM]   [3] Line 48, jwp_votewardenkick.sp::Command_WardenVoteKick
