### ISSUE TITLE
onlrstart new warden choose

### ISSUE THREAD

**Issue by WhyFaust** [TiBarification/Jail-Warden-Pro#52]
Когда начинается лр(T==2) сносит кмд и выбирает нового рандомно
`jwp_choose_mode "3"`

**Comment by TiBarification** [comment]
Было исправлено в коммите: f4305aca

**Comment by WhyFaust** [comment]
К примеру когда игроков мало(2 т и 1 кт,то кмд всё равно его назначает,хотя у  них лр

**Comment by TiBarification** [comment]
Версия ядра?

**Comment by TiBarification** [comment]
На версии 1.1.2 я исправил проблему с назначением кмд при `jwp_choose_mode "3"`

**Comment by WhyFaust** [comment]
> 1.1.2

**Comment by WhyFaust** [comment]
Странно,у меня то на этой версии осталась ошибка(
