### ISSUE TITLE
kick ct error

### ISSUE THREAD

**Issue by WhyFaust** [TiBarification/Jail-Warden-Pro#53]
04/17/2017 - 17:37:46: [SM] Exception reported: Client index 1702129494 is invalid
L 04/17/2017 - 17:37:46: [SM] Blaming: jwp_votewardenkick.smx
L 04/17/2017 - 17:37:46: [SM] Call stack trace:
L 04/17/2017 - 17:37:46: [SM]   [0] VFormat
L 04/17/2017 - 17:37:46: [SM]   [1] Line 68, C:\Users\Faust-PC\Desktop\scripting\include\multicolors.inc::CPrintToChatAll
L 04/17/2017 - 17:37:46: [SM]   [2] Line 105, jwp_votewardenkick.sp::VoteForPlayer
L 04/17/2017 - 17:37:46: [SM]   [3] Line 48, jwp_votewardenkick.sp::Command_WardenVoteKick

**Comment by TiBarification** [comment]
Fixed in commit ffca1ba
