### ISSUE TITLE
Warden AFK Module

### ISSUE THREAD

**Issue by TiBarification** [TiBarification/Jail-Warden-Pro#56]
After warden chosed, if he is afk, force him to resign and choose another warden by priority:
1. warden zam (deputy).
2. Random ct.

**Comment by WhyFaust** [comment]
Блин,а у меня уже в приват реализовали :-(
Ну конечно не так,как написано.А после выбора кмд,у меня стоит по голосованию,если он афк,то его убивает и получает предупреждение.Если и в след раунде так же,то перекидывает за Т команду

**Comment by WhyFaust** [comment]
#64

**Comment by WhyFaust** [comment]
Можно же закрыть уже?)
