### ISSUE TITLE
Mute for admin

### ISSUE THREAD

**Issue by fakeoff0** [TiBarification/Jail-Warden-Pro#57]
Подскажите как сделать чтобы мут давался админам в модуле jwp_bequiet и jwp_mute

**Comment by TiBarification** [comment]
### jwp_bequiet ###
Убрать выделенное содержимое [(строка 34-36)](../blob/master/addons/sourcemod/scripting/jwp_bequiet.sp#L34-L36)
### jwp_mute ###
Здесь будет сложнее.
Убрать содержимое [(строка 263-265)](../blob/master/addons/sourcemod/scripting/jwp_mute.sp#L263-L265)
На строке [266](../blob/master/addons/sourcemod/scripting/jwp_mute.sp#L266) изменить на:

```h
return (IsClientInGame(client) && !IsFakeClient(client) && GetClientTeam(client) == CS_TEAM_T && IsPlayerAlive(client));
```

**Comment by fakeoff0** [comment]
Спасибо, за одно хочу узнать как убрать csay, сообщение которое выделяется важным. Всем слушать Кмд (Не видно счетчик  shop_jetpack и shop_jihad)

**Comment by TiBarification** [comment]
Уберите на строке [33](../blob/master/addons/sourcemod/scripting/jwp_bequiet.sp#L33)
Соответственно можно и этот блок кода тоже [17-20](../blob/master/addons/sourcemod/scripting/jwp_bequiet.sp#L17-L20)
