### ISSUE TITLE
Increase the distance, pris counter

### ISSUE THREAD

**Issue by fakeoff0** [TiBarification/Jail-Warden-Pro#58]
1. Если в строю Террористов есть малейший промежуток, то оно не подсчитывает их. Как можно увеличить дистанцию подсчета игроков на три игровых шага?
2. Как сделать чтобы подсчет Т, писался в общий чат?

**Comment by TiBarification** [comment]
1. Слишком субъективные величины (игровой шаг). Слишком большие математические вычисления снизят быстродействие плагина. Что в свою очередь увеличит нагрузку, так как обрабатывается позиция каждого игрока. Я подумаю над этим.
2. Нужно заменить:
```h
JWP_ActionMsg(client, 
```
на
```h
JWP_ActionMsgAll(
```

**Comment by WhyFaust** [comment]
Разве так считает?У меня считает сколько игроков видно в поле зрении твоём.А не сколько в строю.

**Comment by TiBarification** [comment]
Строй как позиционирование игрока относительно других игроков? В поле зрения уже решённая задача. Что автор хочет не ясно.

**Comment by kerillovi4** [comment]
Если Т построенный в линию и меж ними есть "дырка" место где они стоят не плотно к друг другу, то плагин их не будет считать, я так думаю.....

**Comment by vovo4ka960** [comment]
как RealFaya сказал, сейчас вот так. А нужно чтобы подсчет был даже с этим промежутком в строю Т
