### ISSUE TITLE
Errors log jwp core

### ISSUE THREAD

**Issue by fakeoff0** [TiBarification/Jail-Warden-Pro#59]
Добрый день! Возможно ли исправить это?

> L 07/03/2017 - 12:35:42: [SM] Exception reported: Invalid <JSON Object> handle 0 (error 4)
L 07/03/2017 - 12:35:42: [SM] Blaming: jwp_core.smx
L 07/03/2017 - 12:35:42: [SM] Call stack trace:
L 07/03/2017 - 12:35:42: [SM]   [0] json_typeof
L 07/03/2017 - 12:35:42: [SM]   [1] Line 970, /home/travis/build/TiBarification/Jail-Warden-Pro/addons/sourcemod/scripting/include/smjansson.inc::json_object_get_bool
L 07/03/2017 - 12:35:42: [SM]   [2] Line 245, jwp/dev.sp::GetStatusEnd
L 07/03/2017 - 12:35:42: [SM]   [4] SteamWorks_GetHTTPResponseBodyCallback
L 07/03/2017 - 12:35:42: [SM]   [5] Line 233, jwp/dev.sp::OnSteamWorksHTTPRequestCompleted
L 07/03/2017 - 12:57:22: [SM] Exception reported: Invalid <JSON Object> handle 0 (error 4)
L 07/03/2017 - 12:57:22: [SM] Blaming: jwp_core.smx
L 07/03/2017 - 12:57:22: [SM] Call stack trace:
L 07/03/2017 - 12:57:22: [SM]   [0] json_typeof
L 07/03/2017 - 12:57:22: [SM]   [1] Line 970, /home/travis/build/TiBarification/Jail-Warden-Pro/addons/sourcemod/scripting/include/smjansson.inc::json_object_get_bool
L 07/03/2017 - 12:57:22: [SM]   [2] Line 245, jwp/dev.sp::GetStatusEnd
L 07/03/2017 - 12:57:22: [SM]   [4] SteamWorks_GetHTTPResponseBodyCallback
L 07/03/2017 - 12:57:22: [SM]   [5] Line 233, jwp/dev.sp::OnSteamWorksHTTPRequestCompleted
L 07/03/2017 - 12:57:39: [SM] Exception reported: Invalid <JSON Object> handle 0 (error 4)
L 07/03/2017 - 12:57:39: [SM] Blaming: jwp_core.smx
L 07/03/2017 - 12:57:39: [SM] Call stack trace:
L 07/03/2017 - 12:57:39: [SM]   [0] json_typeof
L 07/03/2017 - 12:57:39: [SM]   [1] Line 970, /home/travis/build/TiBarification/Jail-Warden-Pro/addons/sourcemod/scripting/include/smjansson.inc::json_object_get_bool
L 07/03/2017 - 12:57:39: [SM]   [2] Line 245, jwp/dev.sp::GetStatusEnd
L 07/03/2017 - 12:57:39: [SM]   [4] SteamWorks_GetHTTPResponseBodyCallback
L 07/03/2017 - 12:57:39: [SM]   [5] Line 233, jwp/dev.sp::OnSteamWorksHTTPRequestCompleted
L 07/03/2017 - 12:58:45: [SM] Exception reported: Invalid <JSON Object> handle 0 (error 4)
L 07/03/2017 - 12:58:45: [SM] Blaming: jwp_core.smx
L 07/03/2017 - 12:58:45: [SM] Call stack trace:
L 07/03/2017 - 12:58:45: [SM]   [0] json_typeof
L 07/03/2017 - 12:58:45: [SM]   [1] Line 970, /home/travis/build/TiBarification/Jail-Warden-Pro/addons/sourcemod/scripting/include/smjansson.inc::json_object_get_bool
L 07/03/2017 - 12:58:45: [SM]   [2] Line 245, jwp/dev.sp::GetStatusEnd
L 07/03/2017 - 12:58:45: [SM]   [4] SteamWorks_GetHTTPResponseBodyCallback
L 07/03/2017 - 12:58:45: [SM]   [5] Line 233, jwp/dev.sp::OnSteamWorksHTTPRequestCompleted
L 07/03/2017 - 13:39:50: Error log file session closed.
L 07/03/2017 - 13:39:52: SourceMod error session started

>

**Comment by TiBarification** [comment]
Already fixed
