### ISSUE TITLE
Laserbeam

### ISSUE THREAD

**Issue by WhyFaust** [TiBarification/Jail-Warden-Pro#60]
Как сделать,чтобы он изначально был включен,а только после в кмд его можно выключать?!
И как поменять стандартный красный цвет,к примеру на радужный

**Comment by WhyFaust** [comment]
Включить по стандарту смог,заменив на 124 строчке с false на true

**Comment by TiBarification** [comment]
Приму к сведению

**Comment by fakeoff0** [comment]
Можно добавить, чтобы луч можно было увидеть через препятствия или стены
