### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by WhyFaust** [TiBarification/Jail-Warden-Pro#65]
L 08/06/2017 - 03:31:02: [SM] Exception reported: Invalid <JSON Object> handle 0 (error 4)
L 08/06/2017 - 03:31:02: [SM] Blaming: jwp_core.smx
L 08/06/2017 - 03:31:02: [SM] Call stack trace:
L 08/06/2017 - 03:31:02: [SM]   [0] json_typeof
L 08/06/2017 - 03:31:02: [SM]   [1] Line 970, C:\Users\mrkos\Desktop\scripting\include\smjansson.inc::json_object_get_bool
L 08/06/2017 - 03:31:02: [SM]   [2] Line 221, jwp/dev.sp::GetStatusEnd
L 08/06/2017 - 03:31:02: [SM]   [4] SteamWorks_GetHTTPResponseBodyCallback
L 08/06/2017 - 03:31:02: [SM]   [5] Line 209, jwp/dev.sp::OnSteamWorksHTTPRequestCompleted

**Comment by TiBarification** [comment]
Duplicate #59

**Comment by WhyFaust** [comment]
Но у меня стоит последняя версия ядра,а там написано,что уже исправлено
