### ISSUE TITLE
bequiet

### ISSUE THREAD

**Issue by fakeoff0** [TiBarification/Jail-Warden-Pro#68]
Перестал работать модуль jwp_bequiet после обновления cs:go, подскажите как решить проблему

**Comment by TiBarification** [comment]
Попробуйте обновить [gamedata](https://github.com/Franc1sco/VoiceAnnounceEX/blob/master/gamedata/voiceannounce_ex.games.txt)

**Comment by fakeoff0** [comment]
Работает.
А как сделать чтобы мут давался всем, исключение администратору флагу z
if (GetUserAdmin(i) != INVALID_ADMIN_ID)
SetClientListeningFlags(i, VOICE_NORMAL);
else
Это оставить?

**Comment by fakeoff0** [comment]
И еще хотел попросить, если вам не сложно
Можете сделать чтобы в меню кмд было включение и выключение модуля jwp_bequiet . Было бы очень классно

**Comment by TiBarification** [comment]
Подумаем над этим.

**Comment by WhyFaust** [comment]
https://github.com/mrkos9i4ok/Jail-Warden-Pro/commit/ccbf709ae8ca15c02af3a7659948f12534673e82

**Comment by WhyFaust** [comment]
Посмотри ту ветку,по сути должно работать)

**Comment by WhyFaust** [comment]
#70
