### ISSUE TITLE
JWP Icon - Bad Sprite

### ISSUE THREAD

**Issue by suremiur** [TiBarification/Jail-Warden-Pro#71]
**Добрый вечер.**
Возникает проблема с иконкой над головой у кмд. Ну как сказать. Ее просто нет, а консоль забивается кучей ошибок когда смотришь в сторону кмд:
_s: Bad sprite type 1065353216
GetSpriteAxes: Bad sprite type 1065353216
s: Bad sprite type 1065353216
GetSpriteAxes: Bad sprite type 1065353216_

Прописано все верно, на фастдл залито, не понимаю в чем беда/
Игра CSS, логи чисты.

**Comment by TiBarification** [comment]
А сторонний плагин-загрузчик файлов установлен? И если так, то в нём прописаны пути для скачивания текстуры?

**Comment by suremiur** [comment]
Да, пути прописаны, текстуры скачиваются. Также текстуры лежат и на фастдл. В VMT файлах указаны верно пути.  Не понимаю в чем беда, еще и ни у кого не видел подобной ошибки..

**Comment by TiBarification** [comment]
https://github.com/TiBarification/Jail-Warden-Pro/blob/master/cfg/jwp/icon.cfg
Конфигурация не изменена?

**Comment by suremiur** [comment]
**Огромное спасибо!** Проблема решена путем полной замены файлов модуля на стандартные файлы. Сначала не работало, и я решил поменять пути, везде сменил, но видимо это не поддерживалось почему-то! 
Спасибо еще раз за помощь и за отличный плагин!
