### ISSUE TITLE
Добавить/Исправить

### ISSUE THREAD

**Issue by xMaZax** [TiBarification/Jail-Warden-Pro#72]
**Установка игровых дней (со звуками,оверлеями,с кд)**
Война - КТ против Т, командный ДМ
Свобода всем - ДМ
Зомби - КТ(зомби) против Т(людей), урезанная zombiereloaded
НоСкоп - НоуСкоп ДМ с маленькой гравитацией & выбранной или рандомной винтовкой(скар,авп и т.д.)
Битва на гранатах - Гранатовый ДМ с маленький гравитацией
Прятки в темноте - CT(Ищут) против T(Прячутся), как будто hideNseek
Поймать и заморозить - КТ должны поймать всех Т(заморозить)
Охота на уток - КТ(Охотники) с новами(дробовики) против Т(утками с видом от 3 лица) с гранатами
Суицидник с бомбой - Т должны взорвать бомбы, убив себя и КТ
Пьяный - ДМ с плохими условиями
День Урона(Наноси урон) - Нанести как можно больше урона оппонентам. Побеждает команда, которая нанесла больше всего урона.
Зевс - ДМ с зевсом. При каждом новом убийстве получение нового зевса.
Олимпийский огонь - Случайных игрок подожжён. Он будет гореть, пока не передаст огонь кому-то другому.
Ковбой - ДМ с револьверами или беретами.
Ножи - ДМ на ножах с различной конфигурацией. Гравитация, вид от 3 лица, коньками.
Фридей - Автоматический фридей на первом раунде &/или когда нету КТ

**Добавить звуки отсчета в таймер**
**АвтоМут на какое то время вначале раунда** ps: с поддержкой SB refork
от sm_hosties не пашет.
**Установка иконов зекам и замам*
**Отдельные права для замов с доступом  к !w**

**Comment by fakeoff0** [comment]
Отключите модуль jwp_bequiet и будет работать мут в начале раунда

**Comment by WhyFaust** [comment]
Зачем что то тырить с другого ядра.Вы перечислили всё,что есть в MyJB?
А можно придумать что-то своё уникальное.
