### ISSUE TITLE
LaserBeaam,Core

### ISSUE THREAD

**Issue by WanekWest** [TiBarification/Jail-Warden-Pro#79]
L 01/26/2020 - 00:22:06: [SM] Exception reported: Instruction contained invalid parameter
L 01/26/2020 - 00:22:06: [SM] Blaming: jwp/jwp_core.smx
L 01/26/2020 - 00:22:06: [SM] Call stack trace:
L 01/26/2020 - 00:22:06: [SM]   [0] Call_Finish
L 01/26/2020 - 00:22:06: [SM]   [1] Line 60, addons/sourcemod/scripting/jwp/forwards.sp::Forward_OnWardenResigned
L 01/26/2020 - 00:22:06: [SM]   [2] Line 261, addons/sourcemod/scripting/jwp_core.sp::Event_OnRoundEnd
L 01/26/2020 - 00:22:06: [SM]   [4] ChangeClientTeam
L 01/26/2020 - 00:22:06: [SM]   [5] Line 367, C:\Users\САША\YandexDisk\Плагины\Ultimate Jail Balancer\scripting\ujb.sp::ChangeTeamTimer

L 01/26/2020 - 00:28:29: [SM] Exception reported: Instruction contained invalid parameter
L 01/26/2020 - 00:28:29: [SM] Blaming: jwp/jwp_laserbeam.smx
L 01/26/2020 - 00:28:29: [SM] Call stack trace:
L 01/26/2020 - 00:28:29: [SM]   [0] Menu.Display
L 01/26/2020 - 00:28:29: [SM]   [1] Line 144, addons/sourcemod/scripting/jwp_laserbeam.sp::OnFuncSelect
L 01/26/2020 - 00:28:29: [SM]   [3] Call_Finish
L 01/26/2020 - 00:28:29: [SM]   [4] Line 254, addons/sourcemod/scripting/jwp/jwpm_menu.sp::Cmd_ShowMenu_Handler

**Comment by TiBarification** [comment]
There are no information about this error to reproduce it. Please be more informative.

Use format like that:
```**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Server (please complete the following information):**
 - OS: [e.g. Linux]
 - Sourcemod version [e.g. 1.8.0-git1846]
 - Version [e.g. 3.0]

**Additional context**
Add any other context about the problem here.
```
