### ISSUE TITLE
Logs spam

### ISSUE THREAD

**Issue by ifrag-ru** [TiBarification/Jail-Warden-Pro#80]
**Describe the bug**
L 11/24/2020 - 16:21:27: [SM] Exception reported: A vote is already in progress
L 11/24/2020 - 16:21:27: [SM] Blaming: jwphud.smx
L 11/24/2020 - 16:21:27: [SM] Call stack trace:
L 11/24/2020 - 16:21:27: [SM]   [0] VoteMenu
L 11/24/2020 - 16:21:27: [SM]   [1] Line 797, D:\Dekstop\Работа\COMPILE\include\menus.inc::VoteMenuToAll
L 11/24/2020 - 16:21:27: [SM]   [2] Line 404, D:\Dekstop\Работа\COMPILE\jwphud.sp::CallBack_VoteGame
L 11/24/2020 - 16:52:57: Error log file session closed.

**Server (please complete the following information):**
 - OS: Linux
 - Sourcemod version SourceMod Version: 1.10.0.6499

**Comment by TiBarification** [comment]
Not related to the core.

**Comment by ifrag-ru** [comment]
I agree, but the flood gets in the way :)

**Comment by TiBarification** [comment]
Unload this module and you will be fine.
