### ISSUE TITLE
last update

### ISSUE THREAD

**Issue by ifrag-ru** [TiBarification/Jail-Warden-Pro#81]
L 12/04/2020 - 13:37:01: [SM] Blaming: jwp_mg.smx
L 12/04/2020 - 13:37:01: [SM] Call stack trace:
L 12/04/2020 - 13:37:01: [SM]   [0] CS_TerminateRound
L 12/04/2020 - 13:37:01: [SM]   [1] Line 316, jwp/mg/events.sp::Event_OnPlayerDeath
L 12/04/2020 - 13:37:01: [SM]   [3] ChangeClientTeam
L 12/04/2020 - 13:37:01: [SM]   [4] Line 1089, addons/sourcemod/scripting/jwp_ratio.sp::Timer_ForceCTSide

**Comment by TiBarification** [comment]
Use this form to provide bug request.

Also if you are providing logs, make sure, that it have line "Exception repoted".

https://github.com/TiBarification/Jail-Warden-Pro/issues/new?template=Bug_report.md
