### ISSUE TITLE
Flood logs

### ISSUE THREAD

**Issue by ifrag-ru** [TiBarification/Jail-Warden-Pro#82]
L 03/29/2021 - 23:32:39: [SM] Exception reported: Client 3 is not in game
L 03/29/2021 - 23:32:39: [SM] Blaming: jwp_skins.smx
L 03/29/2021 - 23:32:39: [SM] Call stack trace:
L 03/29/2021 - 23:32:39: [SM]   [0] SetEntityModel
L 03/29/2021 - 23:32:39: [SM]   [1] Line 309, addons/sourcemod/scripting/jwp_skins.sp::SetActualModel
L 03/29/2021 - 23:32:39: [SM]   [2] Line 295, addons/sourcemod/scripting/jwp_skins.sp::SetModel
L 03/30/2021 - 00:01:31: Error log file session closed.

**Comment by TiBarification** [comment]
Not related to core. Closed

**Comment by TiBarification** [comment]
https://github.com/TiBarification/Jail-Warden-Pro/issues/new?assignees=&labels=&template=Bug_report.md
