### ISSUE TITLE
Баланс КМД

### ISSUE THREAD

**Issue by abcen7** [TiBarification/Jail-Warden-Pro#83]
Здравствуйте, не знаете, где можно настроить отношение баланса к КМД. То есть, чтобы можно было взять кмд, если на сервере меньше 3 игроков

**Comment by TiBarification** [comment]
English only

**Comment by abcen7** [comment]
Hello, you don’t know where you can adjust the balance to KMD ratio. That is, so that you can take a kmd if there are less than 3 players on the server

**Comment by TiBarification** [comment]
> Hello, you don’t know where you can adjust the balance to KMD ratio. That is, so that you can take a kmd if there are less than 3 players on the server

this plugin is not a part of this repository, please use search to find plugin you need
